# coverage:
#   precision: 2
#   round: down
#   threshold: 80  # Enforces a coverage threshold of 80%

# ignore:
#   - cmd/myapp/main.go
#   - domain/*
#   - infraestructure/database/*
#   - infraestructure/persistence/postgres_repository.go
