name: Test and Coverage Validation

on:
  pull_request:
    paths:
      - '**/*.go'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: |
        go mod tidy
        go mod vendor

    - name: Run Tests with Coverage
      run: |
        go test -coverprofile=coverage.out ./...
        go tool cover -func=coverage.out

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.out
        fail_ci_if_error: true

    - name: Check Coverage
      run: |
        COVERAGE_PERCENTAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        REQUIRED_COVERAGE=80  # Set the required coverage percentage

        echo "Coverage: $COVERAGE_PERCENTAGE%"

        if (( $(echo "$COVERAGE_PERCENTAGE < $REQUIRED_COVERAGE" | bc -l) )); then
          echo "Error: Test coverage is below $REQUIRED_COVERAGE% (current: $COVERAGE_PERCENTAGE%)"
          exit 1
        fi
