name: Go Build and Analyze with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'  # Specify the Go version you are using

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests and generate coverage report
      run: |
        go test -v ./... > result.log; tail -n 10 result.log
        go test -coverprofile=coverage.out ./... # This generates coverage.out

    - name: SonarCloud Setup
      uses: sonarsource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run SonarCloud analysis
      run: |
        echo ${{ secrets.SONAR_TOKEN }}  # Verify if the token is being passed
        sonar-scanner \
          -Dsonar.projectKey=gomesmatheus_tc-cliente \
          -Dsonar.projectName="tc-cliente" \
          -Dsonar.sources=./ \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.go.coverageReportPaths=coverage.out

